### ISSUE TITLE
black check failed in Github Action

### ISSUE THREAD

**Issue by leungyukshing** [peterjc/flake8-black#27]
Repo Link: https://github.com/leungyukshing/beta-recsys/runs/1051654901

All the files are formatted and the CI ran successfully before. But recently it failed to pass black check in flake8. I try to black those files(on both Windows10 and Mac) but there is no change.

**Comment by peterjc** [comment]
You are using flake8-black 0.2.1 which has been out over a month, unlikely to be the problem.

I would guess this is due to using black 20.8b1, released 26 August 2020, which does change the output slightly in some cases. Can you check that?

You may wish to pin a specific version of black to avoid this happening again. Currently flake8-black does not care exactly which version of black you have, as long as you use black 19.3b0 or later.

**Comment by leungyukshing** [comment]
You are right! Use a specified version of black may deal with this problem. Anyway, thx for help!
